# Generated by Django 4.0.6 on 2022-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='nazwa wydarzenia')),
                ('short', models.TextField(blank=True, null=True, verbose_name='krótki opis')),
            ],
        ),
    ]
