# Generated by Django 4.0.6 on 2022-07-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferencje', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'wydarzenie', 'verbose_name_plural': 'wydarzenia'},
        ),
        migrations.AddField(
            model_name='event',
            name='miasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preferencje.miasto'),
        ),
        migrations.AddField(
            model_name='event',
            name='opis',
            field=models.TextField(blank=True, null=True, verbose_name='długi opis'),
        ),
        migrations.AddField(
            model_name='event',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='media/event'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preferencje.region'),
        ),
        migrations.AddField(
            model_name='event',
            name='rodzaj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preferencje.rodzaj'),
        ),
    ]
