# Generated by Django 4.0.6 on 2022-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_event_options_event_miasto_event_opis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='media/event/bgs'),
        ),
    ]
