# Generated by Django 4.0.6 on 2022-07-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archiwum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
