# Generated by Django 4.0.6 on 2022-07-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_event_archiwum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bg',
            field=models.ImageField(blank=True, default='media/1.png', null=True, upload_to='media/event/bgs'),
        ),
    ]
