# Generated by Django 4.0.6 on 2022-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mapa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
