# Generated by Django 4.0.6 on 2022-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_event_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='panstwo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ulica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
