# Generated by Django 4.0.6 on 2022-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_event_panstwo_event_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='miasto do mapy'),
        ),
    ]
