# Generated by Django 4.0.6 on 2022-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_event_panstwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ulica',
        ),
        migrations.AddField(
            model_name='event',
            name='w',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='do odmiany'),
        ),
    ]
