# Generated by Django 4.0.6 on 2022-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_event_city_remove_event_ulica_event_w'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mapa',
        ),
        migrations.AddField(
            model_name='event',
            name='adres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
