# Generated by Django 4.0.6 on 2022-07-19 17:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_event_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opis',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
