# Generated by Django 4.0.6 on 2022-07-19 18:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_event_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opis',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
