# Generated by Django 4.0.6 on 2022-07-11 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000, verbose_name='treść')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='data')),
                ('user', models.CharField(max_length=1000000, verbose_name='użytkownik')),
                ('room', models.CharField(max_length=1000000, verbose_name='forum')),
            ],
            options={
                'verbose_name': 'widomość',
                'verbose_name_plural': 'wiadomości',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'forum',
                'verbose_name_plural': 'fora',
            },
        ),
    ]
