# Generated by Django 4.0.6 on 2022-07-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_event_archiwum'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='news.event'),
            preserve_default=False,
        ),
    ]
