# Generated by Django 4.0.6 on 2022-07-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiony',
            },
        ),
        migrations.CreateModel(
            name='Rodzaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwa')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/rodzaje', verbose_name='awatar')),
                ('opis', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rodzaj',
                'verbose_name_plural': 'Rodzaje',
            },
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwa')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='preferencje.region')),
            ],
            options={
                'verbose_name': 'Miasto',
                'verbose_name_plural': 'Miasta',
            },
        ),
    ]
