# Generated by Django 4.0.6 on 2022-07-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='imię')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwisko')),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('choice', models.CharField(choices=[('Event', 'Event'), ('Wystawca', 'Wystawca'), ('Organizacja', 'Organizacja'), ('Inne', 'Inne')], max_length=500, null=True, verbose_name='wybór')),
                ('temat', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='treść wiadomości')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'wiadomość formularza',
                'verbose_name_plural': 'wiadomości formularza',
            },
        ),
    ]
