# Generated by Django 4.0.6 on 2022-07-07 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='nazwisko')),
                ('tel', models.IntegerField(blank=True, null=True, verbose_name='numer telefonu')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organizator', models.BooleanField(blank=True, default=False, null=True)),
                ('wystawca', models.BooleanField(blank=True, default=False, null=True)),
                ('administrator', models.BooleanField(blank=True, default=False, null=True)),
                ('img', models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
