# Generated by Django 4.0.6 on 2022-07-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencje', '0001_initial'),
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='miasto',
            field=models.ManyToManyField(blank=True, to='preferencje.miasto'),
        ),
        migrations.AddField(
            model_name='profil',
            name='region',
            field=models.ManyToManyField(blank=True, to='preferencje.region'),
        ),
    ]
