# Generated by Django 4.0.6 on 2022-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_event_created_at'),
        ('acc', '0004_alter_profil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='event',
            field=models.ManyToManyField(blank=True, to='news.event', verbose_name='wydarzenie'),
        ),
    ]
