# Generated by Django 4.0.6 on 2022-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_profil_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='imię'),
        ),
    ]
