# Generated by Django 4.0.6 on 2022-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_profil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='img1',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='img2',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='img3',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='img4',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='img5',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='img6',
            field=models.ImageField(blank=True, default='media/1.png', upload_to='media/profile/galeria/'),
        ),
    ]
