# Generated by Django 4.0.6 on 2022-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_profil_adres_profil_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='sex',
            field=models.CharField(choices=[('żeńska', 'żeńska'), ('męska', 'męska')], default=1, max_length=255, verbose_name='płeć'),
            preserve_default=False,
        ),
    ]
