# Generated by Django 4.0.6 on 2022-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0009_profil_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='sex',
            field=models.CharField(choices=[('żeńska', 'żeńska'), ('męska', 'męska')], max_length=255, null=True, verbose_name='płeć'),
        ),
    ]
